server:
  port: 8989
spring:
  application:
    name: spring-boot-batch
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    show_sql: true
  batch:
    job:
      enabled: false
input:
  file: classpath:user-data.csv